# Site settings
title: sethc23
#email: sethc23@users.noreply.github.com
baseurl: ""
url: "http://sethc23.github.io"
github_username:  sethc23

# Social Media
github_url: "https://github.com/sethc23"
linkedin_url: "https://www.linkedin.com/pub/seth-t-chase/16/454/724"
facebook_url: "https://www.facebook.com/public/Seth-Chase"
#twitter_url: ""
#google_plus_url: ""
#stack_exchange_url: ""
#stack_overflow_url: ""

# Build settings
markdown: kramdown
