
# Site settings
title: sethc23
email: sethc23@users.noreply.github.com
emailtext: sethc23
#description:          # THIS COULD/SHOULD BE OCCUPATION DESCRIPTOR
baseurl: ""
url: "http://sethc23.github.io"
github_username:  sethc23

# Social Media
github_url: "https://github.com/sethc23"
linkedin_url: "https://www.linkedin.com/pub/seth-t-chase/16/454/724"
facebook_url: "https://www.facebook.com/public/Seth-Chase"

copy_year: 2016

collections:
  - tabs
  - wiki

collections:
  tabs:
    output: true

  wiki:
    output: true
    #permalink: /wiki/:path/
    defaults:
      - scope:
          path: ""
        values:
          layout: wiki




### -------------------------------------------------
### -------------------------------------------------


# GLOBAL CONFIGURATIONS

# BUILD COMMAND OPTS:
#   -w, --[no-]watch        # watch for changes
#   --config FILE1[,FILE2,...]
#   --drafts                # Process and render draft posts.
#   --future                #Publish posts with a future date.
#   --lsi                   # Produce an index for related posts.
#   --limit_posts NUM       # Limit the number of posts to parse and publish.
#   --force_polling         # Force watch to use polling.
#   -V, --verbose
#   -q, --quiet


# SERVE COMMAND OPTS:
#   --port PORT
#   --host HOSTNAME          # Listen at the given hostname.
#   --baseurl                # URL Serve the website from the given base URL
#   -B, --detach             # Detach the server from the terminal
#   --skip-initial-build     # Skips the initial site build which occurs before the server is started.


# FRONT MATTER
#permalink
#published
#category
#categories
#tags


# DEFAULT SETTINGS
# Where things are
#source:                         ./
#destination:                    ./_site
#plugins_dir:                    ./_plugins
#layouts_dir:                    ./_layouts
#data_dir:                       ./_data
#includes_dir:                   ./_includes
# collections:                    null
#   posts:
#     output:   true

# Handling Reading
safe:                           false
include:                        [".htaccess"]
exclude:                        ["node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files:                     [".git", ".svn"]
encoding:                       "utf-8"
markdown_ext:                   "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts:                    null
limit_posts:                    0
future:                         false
unpublished:                    false

# Plugins
whitelist:                      []
gems:                           [
                                  "jekyll-sitemap"
                                  ,"octopress-date-format"
                                  ,"octopress-debugger"
                                  ,"jekyll-paginate"
                                ]

# Conversion
markdown:                       kramdown
highlighter:                    rouge
lsi:                            false
excerpt_separator:              "\n\n"
incremental:                    false

# Serving
detach:                         false
port:                           28901
host:                           0.0.0.0
baseurl:                        "" # does not include hostname
show_dir_listing:               false

# Outputting
#permalink:                      date
permalink:                      /:year/:month/:day/:title/
#paginate_path:                  /page:num
paginate:                       10
paginate_path:                  "page:num"
timezone:                       America/New_York

quiet:                          false
verbose:                        false
defaults:                       []

liquid:
  error_mode:                   warn

# Markdown Processors
rdiscount:
  extensions:                   ["generate_toc"]

redcarpet:
  extensions:                   [
                                "no_intra_emphasis"
                                ,"tables"
                                ,"fenced_code_blocks"
                                ,"autolink"
                                #,"disable_indented_code_blocks"
                                ,"strikethrough"
                                ,"lax_spacing"
                                ,"space_after_headers"
                                ,"superscript"
                                ,"underline"
                                ,"highlight"
                                ,"quote"
                                ,"footnotes"
                                ]

kramdown:
  auto_id_prefix:               ''
  auto_id_stripping:            false
  auto_ids:                     true
  coderay_bold_every:           10
  coderay_css:                  style
  # coderay_css:                  static/css/ub4.css
  # enable_coderay:               true
  syntax_highlighter:           coderay
  # coderay_default_lang:         markdown
  coderay_line_number_start:    1           # default: 1
  coderay_line_numbers:         nil         # :table, :inline or nil.
  coderay_tab_width:            4
  coderay_wrap:                 div         # :span, :div or nil.
  entity_output:                as_input    # as_input, numeric, symbolic, as_char (default)
  footnote_backlink:            ‘&8617;’    # default
  footnote_nr:                  1           # number of first footnote
  gfm_quirks:                   ["paragraph_end"]
  hard_wrap:                    false
  header_offset:                0           # default:0
  html_to_native:               true
  input:                        GFM
  latex_headers:                section,subsection,subsubsection,paragraph,subparagraph,subparagraph
  # line_width:                   72
  link_defs:                    {}          # predefines link def.s
  math_engine:                  {}
  math_engine_opt:              {}
  parse_block_html:             false
  parse_span_html:              false
  remove_block_html_tags:       false
  remove_span_html_tags:        false
  smart_quotes:                 lsquo,rsquo,ldquo,rdquo
  template:                     ''
  toc_levels:                   1..6
  transliterated_header_ids:    false

    # kramdown Syntax:          http://kramdown.gettalong.org/syntax.html
    # kramdown Quick Reference: http://kramdown.gettalong.org/quickref.html
    # kramdown Options:         https://kramdown.gettalong.org/rdoc/Kramdown/Options.html

    # Set per-document Kramdown command-line options in file
    # {::options auto_ids="false" footnote_nr="5" /}

# ------------------------------
# ------------------------------

